### PR TITLE
Updates needed for Wurm Unlimited 1.6

### PR DESCRIPTION
**Pull request by duejensen**

### CODE REVIEW

**Comment by encode32** [comment]
Thanks for contribute.

**Comment by encode32** [comment]
There is a typo on code, will be resolved.

Should be:
`float curX = tileX * 4 - ox;`
`float curY = tileY * 4 - oy;`
`float nextX = (tileX + 1) * 4 - ox;`
`float nextY = (tileY + 1) * 4 - oy;`

**Comment by duejensen** [comment]
Yeah you are right - sorry about that  - I handedited on Github

**Comment by encode32** [comment]
Don't worry.

**Pull request merged**
